package com.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import com.model.bill;
import com.model.product;
import com.util.connectionClass;

public class billDao {
	public double displayBill(ArrayList<product> bill,String s)
	{
		
		System.out.println("-----------------------------------------");
		System.out.println("Bid \t Bdiscription \t Bprice");
		System.out.println("-----------------------------------------");
		double amount =0;
		 for(product p: bill)
		 {
			 
			System.out.println(p.getPid()+"\t"+p.getPname()+" \t"+p.getPprice()); 
			amount+=p.getPprice();
		 }
		 System.out.println("-----------------------------------------");
		 System.out.println("\t\t amount ="+amount);
		 System.out.println("-----------------------------------------");
		 System.out.println(" Bill Generated by: ="+s);
		 System.out.println("-----------------------------------------");
		return amount;
	}
	
	public int insertBill(bill b)
	{
		int check=0;
		Connection con =new connectionClass().connectionStart();
		PreparedStatement pst =null;
		String sql = "INSERT INTO bill (bdiscription, bamount, bgby) VALUES(?,?,?)";
		try {
			pst=con.prepareStatement(sql);
			//pst.setInt(1, b.getBid());
			pst.setString(1,b.getBdiscription());
			pst.setDouble(2, b.getBamount());
			pst.setString(3, b.getBgby());
			check= pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		finally {
			new connectionClass().connectionClose(pst, con);
		}
		
		
		return check;
	}
	public List<bill> displayAllbill() {
		List<bill> list = new ArrayList();
		Connection con = new connectionClass().connectionStart();
		PreparedStatement pst = null;
		ResultSet rs = null;

		String sql = "select bid, bdiscription,bamount,bgby from bill ";
		
		try {
			pst = con.prepareStatement(sql);
			rs = pst.executeQuery();
			while (rs.next()) {
				bill b1 = new bill();
				b1.setBid((int) rs.getObject("bid"));
			
				b1.setBdiscription((String) rs.getObject("bdiscription"));
				b1.setBamount((double) rs.getObject("bamount"));
				b1.setBgby((String) rs.getObject("bgby"));
				list.add(b1);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		finally {
			new connectionClass().connectionClose(rs, pst, con);
		}

		return list;

	}
	
	

}
